openapi: 3.0.3
info:
  title: ${PROJECT_NAME:-Katesthe-core} API
  version: ${PROJECT_VERSION:-1.0.0}
  description: ${PROJECT_DESCRIPTION:-serves as a django rest_framework starting point}
paths: {}
components: {}
