"""Machine-readable error codes (namespaced UPPER_SNAKE_CASE).

Universal, domain-agnostic codes only. Each constant's value is exactly its
own name, e.g. ``AUTH__UNAUTHENTICATED = "AUTH__UNAUTHENTICATED"``.

Some codes are forward-looking: defined here for the catalog contract but
not yet emitted by any live endpoint (see subtask notes).
"""

# AUTH
AUTH__UNAUTHENTICATED = "AUTH__UNAUTHENTICATED"
AUTH__TOKEN_EXPIRED = "AUTH__TOKEN_EXPIRED"
AUTH__TOKEN_INVALID = "AUTH__TOKEN_INVALID"
AUTH__INVALID_CREDENTIALS = "AUTH__INVALID_CREDENTIALS"
AUTH__ACCOUNT_INACTIVE = "AUTH__ACCOUNT_INACTIVE"
AUTH__PASSWORD_RESET_DISABLED = "AUTH__PASSWORD_RESET_DISABLED"
AUTH__EMAIL_VERIFICATION_DISABLED = "AUTH__EMAIL_VERIFICATION_DISABLED"

# VALIDATION
VALIDATION__MISSING_FIELD = "VALIDATION__MISSING_FIELD"
VALIDATION__INVALID_FORMAT = "VALIDATION__INVALID_FORMAT"
VALIDATION__INVALID_VALUE = "VALIDATION__INVALID_VALUE"

# PERMISSION
PERMISSION__DENIED = "PERMISSION__DENIED"
PERMISSION__INSUFFICIENT_ROLE = "PERMISSION__INSUFFICIENT_ROLE"

# RESOURCE
RESOURCE__NOT_FOUND = "RESOURCE__NOT_FOUND"
RESOURCE__ALREADY_EXISTS = "RESOURCE__ALREADY_EXISTS"
RESOURCE__CONFLICT = "RESOURCE__CONFLICT"

# RATE_LIMIT
RATE_LIMIT__EXCEEDED = "RATE_LIMIT__EXCEEDED"

# INTERNAL
INTERNAL__ERROR = "INTERNAL__ERROR"
INTERNAL__SERVICE_UNAVAILABLE = "INTERNAL__SERVICE_UNAVAILABLE"

# NOTIFICATION
NOTIFICATION__EMAIL_DELIVERY_FAILED = "NOTIFICATION__EMAIL_DELIVERY_FAILED"


class E:
    """Namespace accessor exposing the same codes, e.g. ``E.RESOURCE__NOT_FOUND``."""

    # AUTH
    AUTH__UNAUTHENTICATED = AUTH__UNAUTHENTICATED
    AUTH__TOKEN_EXPIRED = AUTH__TOKEN_EXPIRED
    AUTH__TOKEN_INVALID = AUTH__TOKEN_INVALID
    AUTH__INVALID_CREDENTIALS = AUTH__INVALID_CREDENTIALS
    AUTH__ACCOUNT_INACTIVE = AUTH__ACCOUNT_INACTIVE
    AUTH__PASSWORD_RESET_DISABLED = AUTH__PASSWORD_RESET_DISABLED
    AUTH__EMAIL_VERIFICATION_DISABLED = AUTH__EMAIL_VERIFICATION_DISABLED

    # VALIDATION
    VALIDATION__MISSING_FIELD = VALIDATION__MISSING_FIELD
    VALIDATION__INVALID_FORMAT = VALIDATION__INVALID_FORMAT
    VALIDATION__INVALID_VALUE = VALIDATION__INVALID_VALUE

    # PERMISSION
    PERMISSION__DENIED = PERMISSION__DENIED
    PERMISSION__INSUFFICIENT_ROLE = PERMISSION__INSUFFICIENT_ROLE

    # RESOURCE
    RESOURCE__NOT_FOUND = RESOURCE__NOT_FOUND
    RESOURCE__ALREADY_EXISTS = RESOURCE__ALREADY_EXISTS
    RESOURCE__CONFLICT = RESOURCE__CONFLICT

    # RATE_LIMIT
    RATE_LIMIT__EXCEEDED = RATE_LIMIT__EXCEEDED

    # INTERNAL
    INTERNAL__ERROR = INTERNAL__ERROR
    INTERNAL__SERVICE_UNAVAILABLE = INTERNAL__SERVICE_UNAVAILABLE

    # NOTIFICATION
    NOTIFICATION__EMAIL_DELIVERY_FAILED = NOTIFICATION__EMAIL_DELIVERY_FAILED
